### ISSUE TITLE
Possible incorrect line-ending

### ISSUE THREAD

**Issue by BenjaminGK** [Inventsable/bombino-commands#5]
After upgrading Bombino commnands to the latest I have found  that I no longer can use any of the commands as I get an "env: node\r: No such file or directory" error. 
I should note that I'm on a Mac and by changing index.js to LF it will work properly again.

**Comment by Inventsable** [comment]
Hey! Thanks for the issue report. Can you show what you've done? Do you mean adjusting the `require` statements? Possibly need to check if Mac first via `navigator.platform.indexOf("Mac") > -1` ternary and adjust them

**Comment by BenjaminGK** [comment]
I went into the project where I am I using the bombino-cmd - node_modules -> bombino-commands -> bin and changed the actual index.js line-ending to be LF instead of CRLF using the IDE tool
![Screen Shot 2020-06-29 at 13 20 55](https://user-images.githubusercontent.com/23311430/85979929-9d055380-ba0b-11ea-8a11-89bd871c06d0.png)

This is of cause not something I should have to do but the quickest way to get the commands to work again.

**Comment by Inventsable** [comment]
Thanks. Not sure why this happened and I could've sworn I've never had issues with this previously, but I've tested that LF doesn't throw errors on my side, in which case I switched it as of `1.0.5` to prevent errors on Mac.
